version: '3'

services:
  mq:
    image: rabbitmq:management
    container_name: mq_service
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
    driver: bridge
    external: true
    name: food_guides
